# Generated by Django 4.0 on 2022-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_current_aa_student_is_in_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.ImageField(blank=True, default='company_images/default.png', max_length=1000, null=True, upload_to='C:\\Users\\iyade\\PycharmProjects\\TestStuff\\GIU_Internship_Portal\\media/company_images/'),
        ),
    ]
