# Generated by Django 4.0 on 2022-03-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvbuilder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvbuilder',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.jpg', max_length=1000, null=True, upload_to='C:\\Users\\iyade\\PycharmProjects\\TestStuff\\GIU_Internship_Portal\\media/profile_images/'),
        ),
    ]
